### ISSUE TITLE
Braille Display Locks up After Switching to Japanese 6 Dot Computer Braille

### ISSUE THREAD

**Issue by dangero2000** [aaclause/BrailleExtender#122]
If I go to the NVDA settings and change my braille input/output to Japanese 6 dot Computer braille, the last text reported by the display will not change, and I have to switch back to seemingly any other output table or disable the addon entirely to continue using braille.

This issue is not present if I use Kantenji. After testing Braille Extender with NVDA alpha-28231,648a5d34 (2023.2.0.28231), I have determined that this issue is specific to NVDA JP. Regular versions of NVDA only list Japanese Kantanji as a viable output table, and you cannot input in Japanese at all. The computer braille table only seems to exist in NVDA JP.

Here is the traceback:

Traceback (most recent call last):
  File "eventHandler.pyc", line 300, in executeEvent
  File "eventHandler.pyc", line 101, in __init__
  File "eventHandler.pyc", line 110, in next
  File "D:\NVDAJP\userConfig\addons\BrailleExtender\globalPlugins\brailleExtender\__init__.py", line 223, in event_gainFocus
    if self.backup__brailleTableDict != config.conf["braille"]["translationTable"]: self.reloadBrailleTables()
  File "D:\NVDAJP\userConfig\addons\BrailleExtender\globalPlugins\brailleExtender\__init__.py", line 285, in reloadBrailleTables
    undefinedchars.setUndefinedChar()
  File "D:\NVDAJP\userConfig\addons\BrailleExtender\globalPlugins\brailleExtender\undefinedchars.py", line 81, in setUndefinedChar
    f"undefined {HUCDotPattern}", "ASCII"))
  File "louis\__init__.pyc", line 488, in compileString
RuntimeError: Can't compile entry: tables ['D:\\NVDAJP\\louis\\tables\\ja-jp-comp6.utb', 'D:\\NVDAJP\\louis\\tables\\braille-patterns.cti'], inString b'undefined 12345678-78-12345678'
ERROR - eventHandler.executeEvent (21:46:18.944) - MainThread (4592):
error executing event: gainFocus on <NVDAObjects.Dynamic_UIItemListItemUIA object at 0x064C13F0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 300, in executeEvent
  File "eventHandler.pyc", line 101, in __init__
  File "eventHandler.pyc", line 110, in next
  File "D:\NVDAJP\userConfig\addons\BrailleExtender\globalPlugins\brailleExtender\__init__.py", line 224, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 110, in next
  File "appModules\explorer.pyc", line 506, in event_gainFocus
  File "eventHandler.pyc", line 110, in next
  File "NVDAObjects\UIA\__init__.pyc", line 1341, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1283, in event_gainFocus
  File "braille.pyc", line 2486, in handleGainFocus
  File "braille.pyc", line 2491, in _doNewObject
  File "braille.pyc", line 1949, in getFocusContextRegions
  File "braille.pyc", line 878, in update
  File "D:\NVDAJP\userConfig\addons\BrailleExtender\globalPlugins\brailleExtender\patches.py", line 164, in update
    undefinedchars.undefinedCharProcess(self)
  File "D:\NVDAJP\userConfig\addons\BrailleExtender\globalPlugins\brailleExtender\undefinedchars.py", line 204, in undefinedCharProcess
    startTag = getTextInBraille(startTag)
  File "D:\NVDAJP\userConfig\addons\BrailleExtender\globalPlugins\brailleExtender\utils.py", line 161, in getTextInBraille
    res = [louis.translateString(table, l, mode=louis.ucBrl|louis.dotsIO) for l in t if l]
  File "D:\NVDAJP\userConfig\addons\BrailleExtender\globalPlugins\brailleExtender\utils.py", line 161, in <listcomp>
    res = [louis.translateString(table, l, mode=louis.ucBrl|louis.dotsIO) for l in t if l]
  File "louis\__init__.pyc", line 317, in translateString
RuntimeError: Can't translate: tables ['D:\\NVDAJP\\louis\\tables\\ja-jp-comp6.utb', 'D:\\NVDAJP\\louis\\tables\\braille-patterns.cti'], inbuf b'[\x00\x00\x00', typeform None, mode 68
ERROR - eventHandler.executeEvent (21:46:19.752) - MainThread (4592):
error executing event: gainFocus on <NVDAObjects.Dynamic_MultitaskingViewFrameListItemListItemUIA object at 0x08317870> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 300, in executeEvent
  File "eventHandler.pyc", line 101, in __init__
  File "eventHandler.pyc", line 110, in next
  File "D:\NVDAJP\userConfig\addons\BrailleExtender\globalPlugins\brailleExtender\__init__.py", line 224, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 110, in next
  File "appModules\explorer.pyc", line 506, in event_gainFocus
  File "eventHandler.pyc", line 110, in next
  File "NVDAObjects\UIA\__init__.pyc", line 1341, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1283, in event_gainFocus
  File "braille.pyc", line 2486, in handleGainFocus
  File "braille.pyc", line 2491, in _doNewObject
  File "braille.pyc", line 1985, in getFocusRegions
  File "braille.pyc", line 878, in update
  File "D:\NVDAJP\userConfig\addons\BrailleExtender\globalPlugins\brailleExtender\patches.py", line 164, in update
    undefinedchars.undefinedCharProcess(self)
  File "D:\NVDAJP\userConfig\addons\BrailleExtender\globalPlugins\brailleExtender\undefinedchars.py", line 204, in undefinedCharProcess
    startTag = getTextInBraille(startTag)
  File "D:\NVDAJP\userConfig\addons\BrailleExtender\globalPlugins\brailleExtender\utils.py", line 161, in getTextInBraille
    res = [louis.translateString(table, l, mode=louis.ucBrl|louis.dotsIO) for l in t if l]
  File "D:\NVDAJP\userConfig\addons\BrailleExtender\globalPlugins\brailleExtender\utils.py", line 161, in <listcomp>
    res = [louis.translateString(table, l, mode=louis.ucBrl|louis.dotsIO) for l in t if l]
  File "louis\__init__.pyc", line 317, in translateString
RuntimeError: Can't translate: tables ['D:\\NVDAJP\\louis\\tables\\ja-jp-comp6.utb', 'D:\\NVDAJP\\louis\\tables\\braille-patterns.cti'], inbuf b'[\x00\x00\x00', typeform None, mode 68
ERROR - eventHandler.executeEvent (21:46:20.463) - MainThread (4592):
error executing event: gainFocus on <NVDAObjects.Dynamic_MultitaskingViewFrameListItemListItemUIA object at 0x03CAB0F0> with extra args of {}

**Comment by dangero2000** [comment]
Thanks for the link. I just tested the dev build, and unfortunately, the issue still persists. Do you want me to send my entire log to make it easier to trace?

**Comment by dangero2000** [comment]
> Once this is done, you should be able to select the Japanese 6 Dot Computer Braille as the output braille table without experiencing the error.

It works! :-) Thanks for the help.

**Comment by Saladeuh** [comment]
Hello, same issue here, but the work-arround solution is only working in nvda menus, other windows make the braille display freeze.
Here is a log snippet: 
Traceback (most recent call last):
  File "eventHandler.pyc", line 353, in executeEvent
  File "eventHandler.pyc", line 119, in __init__
  File "eventHandler.pyc", line 128, in next
  File "C:\Users\emili\AppData\Roaming\nvda\addons\focusHighlight\globalPlugins\focusHighlight.py", line 630, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 128, in next
  File "C:\Users\emili\AppData\Roaming\nvda\addons\rdAccess\globalPlugins\rdAccess\__init__.py", line 369, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 128, in next
  File "C:\Users\emili\AppData\Roaming\nvda\addons\goldenCursor\globalPlugins\goldenCursor.py", line 400, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 128, in next
  File "C:\Users\emili\AppData\Roaming\nvda\addons\easyTableNavigator\globalPlugins\easyTableNavigator\__init__.py", line 98, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 128, in next
  File "C:\Users\emili\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\__init__.py", line 168, in event_gainFocus
    if self.backup__brailleTableDict != config.conf["braille"]["translationTable"]: self.reloadBrailleTables()
                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emili\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\__init__.py", line 252, in reloadBrailleTables
    patches.louis.compileString(patches.getCurrentBrailleTables(), bytes(liblouisDef, "ASCII"))
  File "louis\__init__.pyc", line 488, in compileString
RuntimeError: Can't compile entry: tables ['C:\\Users\\emili\\AppData\\Roaming\\nvda/brailleExtender\\brailleDicts\\default.cti', 'C:\\Program Files (x86)\\NVDA\\louis\\tables\\ja-jp-comp6.utb', 'C:\\Program Files (x86)\\NVDA\\louis\\tables\\braille-patterns.cti'], inString b'always \\t 0-0'
ERROR - louisHelper._resolveTable (14:49:25.499) - MainThread (17604):
Traceback (most recent call last):
  File "louisHelper.pyc", line 93, in _resolveTable
  File "louisHelper.pyc", line 93, in <listcomp>
  File "louisHelper.pyc", line 68, in _resolveTableInner
LookupError: Could not resolve table 'C:\\Program Files (x86)\\NVDA\\louis\\tables\\ja-jp-comp6.utb', looked in paths: ['C:\\Program Files (x86)\\NVDA\\louis\\tables']
ERROR - eventHandler.executeEvent (14:49:25.499) - MainThread (17604):
error executing event: gainFocus on <NVDAObjects.Dynamic_VirtualContextMenuRecognizableFileObjectUIAWindowNVDAObject object at 0x087338F0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 353, in executeEvent
  File "eventHandler.pyc", line 119, in __init__
  File "eventHandler.pyc", line 128, in next
  File "C:\Users\emili\AppData\Roaming\nvda\addons\focusHighlight\globalPlugins\focusHighlight.py", line 630, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 128, in next
  File "C:\Users\emili\AppData\Roaming\nvda\addons\rdAccess\globalPlugins\rdAccess\__init__.py", line 369, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 128, in next
  File "C:\Users\emili\AppData\Roaming\nvda\addons\goldenCursor\globalPlugins\goldenCursor.py", line 400, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 128, in next
  File "C:\Users\emili\AppData\Roaming\nvda\addons\easyTableNavigator\globalPlugins\easyTableNavigator\__init__.py", line 98, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 128, in next
  File "C:\Users\emili\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\__init__.py", line 169, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 128, in next
  File "appModules\explorer.pyc", line 496, in event_gainFocus
  File "eventHandler.pyc", line 128, in next
  File "NVDAObjects\UIA\__init__.pyc", line 1581, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1366, in event_gainFocus
  File "braille.pyc", line 2869, in handleGainFocus
  File "braille.pyc", line 2879, in _doNewObject
  File "braille.pyc", line 2293, in getFocusRegions
  File "C:\Users\emili\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\objectpresentation.py", line 156, in update_NVDAObjectRegion
    super(braille.NVDAObjectRegion, self).update()
  File "C:\Users\emili\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\patches.py", line 173, in update_region
    self.brailleCells, self.brailleToRawPos, self.rawToBraillePos, self.brailleCursorPos = louisHelper.translate(
                                                                                           ^^^^^^^^^^^^^^^^^^^^^^
  File "louisHelper.pyc", line 170, in translate
  File "louis\__init__.pyc", line 266, in translate
RuntimeError: Can't translate: tables ['C:\\Users\\emili\\AppData\\Roaming\\nvda/brailleExtender\\brailleDicts\\default.cti', 'C:\\Program Files (x86)\\NVDA\\louis\\tables\\ja-jp-comp6.utb', 'C:\\Program Files (x86)\\NVDA\\louis\\tables\\braille-patterns.cti'], inbuf b'D\x00\x00\x00\xe9\x00\x00\x00m\x00\x00\x00a\x00\x00\x00r\x00\x00\x00r\x00\x00\x00e\x00\x00\x00r\x00\x00\x00 \x00\x00\x00\x8e(\x00\x00\xc0(\x00\x00q(\x00\x00 \x00\x00\x00b\x00\x00\x00s\x00\x00\x00c\x00\x00\x00', typeform None, cursorPos c_long(0), mode 4
ERROR - louisHelper._resolveTable (14:49:25.632) - MainThread (17604):
Traceback (most recent call last):
  File "louisHelper.pyc", line 93, in _resolveTable
  File "louisHelper.pyc", line 93, in <listcomp>
  File "louisHelper.pyc", line 68, in _resolveTableInner
LookupError: Could not resolve table 'C:\\Program Files (x86)\\NVDA\\louis\\tables\\ja-jp-comp6.utb', looked in paths: ['C:\\Program Files (x86)\\NVDA\\louis\\tables']
ERROR - eventHandler.executeEvent (14:49:25.632) - MainThread (17604):
error executing event: gainFocus on <NVDAObjects.Dynamic_VirtualContextMenuRecognizableFileObjectUIAWindowNVDAObject object at 0x06310110> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 353, in executeEvent
  File "eventHandler.pyc", line 119, in __init__
  File "eventHandler.pyc", line 128, in next
  File "C:\Users\emili\AppData\Roaming\nvda\addons\focusHighlight\globalPlugins\focusHighlight.py", line 630, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 128, in next
  File "C:\Users\emili\AppData\Roaming\nvda\addons\rdAccess\globalPlugins\rdAccess\__init__.py", line 369, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 128, in next
  File "C:\Users\emili\AppData\Roaming\nvda\addons\goldenCursor\globalPlugins\goldenCursor.py", line 400, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 128, in next
  File "C:\Users\emili\AppData\Roaming\nvda\addons\easyTableNavigator\globalPlugins\easyTableNavigator\__init__.py", line 98, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 128, in next
  File "C:\Users\emili\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\__init__.py", line 169, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 128, in next
  File "appModules\explorer.pyc", line 496, in event_gainFocus
  File "eventHandler.pyc", line 128, in next
  File "NVDAObjects\UIA\__init__.pyc", line 1581, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1366, in event_gainFocus
  File "braille.pyc", line 2869, in handleGainFocus
  File "braille.pyc", line 2879, in _doNewObject
  File "braille.pyc", line 2293, in getFocusRegions
  File "C:\Users\emili\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\objectpresentation.py", line 156, in update_NVDAObjectRegion
    super(braille.NVDAObjectRegion, self).update()
  File "C:\Users\emili\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\patches.py", line 173, in update_region
    self.brailleCells, self.brailleToRawPos, self.rawToBraillePos, self.brailleCursorPos = louisHelper.translate(
                                                                                           ^^^^^^^^^^^^^^^^^^^^^^
  File "louisHelper.pyc", line 170, in translate
  File "louis\__init__.pyc", line 266, in translate
RuntimeError: Can't translate: tables ['C:\\Users\\emili\\AppData\\Roaming\\nvda/brailleExtender\\brailleDicts\\default.cti', 'C:\\Program Files (x86)\\NVDA\\louis\\tables\\ja-jp-comp6.utb', 'C:\\Program Files (x86)\\NVDA\\louis\\tables\\braille-patterns.cti'], inbuf b'B\x00\x00\x00r\x00\x00\x00a\x00\x00\x00i\x00\x00\x00l\x00\x00\x00l\x00\x00\x00e\x00\x00\x00 \x00\x00\x00D\x00\x00\x00i\x00\x00\x00s\x00\x00\x00p\x00\x00\x00l\x00\x00\x00a\x00\x00\x00y\x00\x00\x00 \x00\x00\x00L\x00\x00\x00o\x00\x00\x00c\x00\x00\x00k\x00\x00\x00s\x00\x00\x00 \x00\x00\x00u\x00\x00\x00p\x00\x00\x00 \x00\x00\x00A\x00\x00\x00f\x00\x00\x00t\x00\x00\x00e\x00\x00\x00r\x00\x00\x00 \x00\x00\x00S\x00\x00\x00w\x00\x00\x00i\x00\x00\x00t\x00\x00\x00c\x00\x00\x00h\x00\x00\x00i\x00\x00\x00n\x00\x00\x00g\x00\x00\x00 \x00\x00\x00t\x00\x00\x00o\x00\x00\x00 \x00\x00\x00J\x00\x00\x00a\x00\x00\x00p\x00\x00\x00a\x00\x00\x00n\x00\x00\x00e\x00\x00\x00s\x00\x00\x00e\x00\x00\x00 \x00\x00\x006\x00\x00\x00 \x00\x00\x00D\x00\x00\x00o\x00\x00\x00t\x00\x00\x00 \x00\x00\x00C\x00\x00\x00o\x00\x00\x00m\x00\x00\x00p\x00\x00\x00u\x00\x00\x00t\x00\x00\x00e\x00\x00\x00r\x00\x00\x00 \x00\x00\x00B\x00\x00\x00r\x00\x00\x00a\x00\x00\x00i\x00\x00\x00l\x00\x00\x00l\x00\x00\x00e\x00\x00\x00 \x00\x00\x00\xb7\x00\x00\x00 \x00\x00\x00I\x00\x00\x00s\x00\x00\x00s\x00\x00\x00u\x00\x00\x00e\x00\x00\x00 \x00\x00\x00#\x00\x00\x001\x00\x00\x002\x00\x00\x002\x00\x00\x00 \x00\x00\x00\xb7\x00\x00\x00 \x00\x00\x00A\x00\x00\x00A\x00\x00\x00C\x00\x00\x00l\x00\x00\x00a\x00\x00\x00u\x00\x00\x00s\x00\x00\x00e\x00\x00\x00/\x00\x00\x00B\x00\x00\x00r\x00\x00\x00a\x00\x00\x00i\x00\x00\x00l\x00\x00\x00l\x00\x00\x00e\x00\x00\x00E\x00\x00\x00x\x00\x00\x00t\x00\x00\x00e\x00\x00\x00n\x00\x00\x00d\x00\x00\x00e\x00\x00\x00r\x00\x00\x00 \x00\x00\x00\x14 \x00\x00 \x00\x00\x00M\x00\x00\x00o\x00\x00\x00z\x00\x00\x00i\x00\x00\x00l\x00\x00\x00l\x00\x00\x00a\x00\x00\x00 \x00\x00\x00F\x00\x00\x00i\x00\x00\x00r\x00\x00\x00e\x00\x00\x00f\x00\x00\x00o\x00\x00\x00x\x00\x00\x00 \x00\x00\x00-\x00\x00\x00 \x00\x00\x001\x00\x00\x00 \x00\x00\x00f\x00\x00\x00e\x00\x00\x00n\x00\x00\x00\xea\x00\x00\x00t\x00\x00\x00r\x00\x00\x00e\x00\x00\x00 \x00\x00\x00e\x00\x00\x00n\x00\x00\x00 \x00\x00\x00c\x00\x00\x00o\x00\x00\x00u\x00\x00\x00r\x00\x00\x00s\x00\x00\x00 \x00\x00\x00d\x00\x00\x00\x19 \x00\x00e\x00\x00\x00x\x00\x00\x00\xe9\x00\x00\x00c\x00\x00\x00u\x00\x00\x00t\x00\x00\x00i\x00\x00\x00o\x00\x00\x00n\x00\x00\x00 \x00\x00\x00b\x00\x00\x00t\x00\x00\x00n\x00\x00\x00 \x00\x00\x001\x00\x00\x00/\x00\x00\x003\x00\x00\x00', typeform None, cursorPos c_long(0), mode 4
ERROR - louisHelper._resolveTable (14:49:26.757) - MainThread (17604):
Traceback (most recent call last):
  File "louisHelper.pyc", line 93, in _resolveTable
  File "louisHelper.pyc", line 93, in <listcomp>
  File "louisHelper.pyc", line 68, in _resolveTableInner
LookupError: Could not resolve table 'C:\\Program Files (x86)\\NVDA\\louis\\tables\\ja-jp-comp6.utb', looked in paths: ['C:\\Program Files (x86)\\NVDA\\louis\\tables']
ERROR - scriptHandler.executeScript (14:49:26.757) - MainThread (17604):
error executing script: <bound method GlobalPlugin.script_win of GlobalPlugin ('globalPlugins.brailleExtender')> with gesture 'espace avec point 2 4 5 6'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 300, in executeScript
  File "C:\Users\emili\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\__init__.py", line 909, in script_win
    if sil: self.getActualModifiers()
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emili\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\__init__.py", line 876, in getActualModifiers
    braille.handler.message('%s...' % s)
  File "C:\Users\emili\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\speechhistorymode.py", line 137, in newBrailleMessage
    orig_BrailleMessage(self, *args, **kwargs)
  File "braille.pyc", line 2820, in message
  File "C:\Users\emili\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\patches.py", line 173, in update_region
    self.brailleCells, self.brailleToRawPos, self.rawToBraillePos, self.brailleCursorPos = louisHelper.translate(
                                                                                           ^^^^^^^^^^^^^^^^^^^^^^
  File "louisHelper.pyc", line 170, in translate
  File "louis\__init__.pyc", line 266, in translate
RuntimeError: Can't translate: tables ['C:\\Users\\emili\\AppData\\Roaming\\nvda/brailleExtender\\brailleDicts\\default.cti', 'C:\\Program Files (x86)\\NVDA\\louis\\tables\\ja-jp-comp6.utb', 'C:\\Program Files (x86)\\NVDA\\louis\\tables\\braille-patterns.cti'], inbuf b'W\x00\x00\x00I\x00\x00\x00N\x00\x00\x00+\x00\x00\x00.\x00\x00\x00.\x00\x00\x00.\x00\x00\x00', typeform None, cursorPos c_long(0), mode 4
ERROR - louisHelper._resolveTable (14:49:27.047) - MainThread (17604):
Traceback (most recent call last):
  File "louisHelper.pyc", line 93, in _resolveTable
  File "louisHelper.pyc", line 93, in <listcomp>
  File "louisHelper.pyc", line 68, in _resolveTableInner
LookupError: Could not resolve table 'C:\\Program Files (x86)\\NVDA\\louis\\tables\\ja-jp-comp6.utb', looked in paths: ['C:\\Program Files (x86)\\NVDA\\louis\\tables']
ERROR - eventHandler.executeEvent (14:49:27.051) - MainThread (17604):
error executing event: gainFocus on <NVDAObjects.Dynamic_VirtualContextMenuRecognizableFileObjectUIAWindowNVDAObject object at 0x06277850> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 353, in executeEvent
  File "eventHandler.pyc", line 119, in __init__
  File "eventHandler.pyc", line 128, in next
  File "C:\Users\emili\AppData\Roaming\nvda\addons\focusHighlight\globalPlugins\focusHighlight.py", line 630, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 128, in next
  File "C:\Users\emili\AppData\Roaming\nvda\addons\rdAccess\globalPlugins\rdAccess\__init__.py", line 369, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 128, in next
  File "C:\Users\emili\AppData\Roaming\nvda\addons\goldenCursor\globalPlugins\goldenCursor.py", line 400, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 128, in next
  File "C:\Users\emili\AppData\Roaming\nvda\addons\easyTableNavigator\globalPlugins\easyTableNavigator\__init__.py", line 98, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 128, in next
  File "C:\Users\emili\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\__init__.py", line 169, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 128, in next
  File "appModules\explorer.pyc", line 496, in event_gainFocus
  File "eventHandler.pyc", line 128, in next
  File "NVDAObjects\UIA\__init__.pyc", line 1581, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1366, in event_gainFocus
  File "braille.pyc", line 2869, in handleGainFocus
  File "braille.pyc", line 2879, in _doNewObject
  File "braille.pyc", line 2293, in getFocusRegions
  File "C:\Users\emili\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\objectpresentation.py", line 156, in update_NVDAObjectRegion
    super(braille.NVDAObjectRegion, self).update()
  File "C:\Users\emili\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\patches.py", line 173, in update_region
    self.brailleCells, self.brailleToRawPos, self.rawToBraillePos, self.brailleCursorPos = louisHelper.translate(
                                                                                           ^^^^^^^^^^^^^^^^^^^^^^
  File "louisHelper.pyc", line 170, in translate
  File "louis\__init__.pyc", line 266, in translate
RuntimeError: Can't translate: tables ['C:\\Users\\emili\\AppData\\Roaming\\nvda/brailleExtender\\brailleDicts\\default.cti', 'C:\\Program Files (x86)\\NVDA\\louis\\tables\\ja-jp-comp6.utb', 'C:\\Program Files (x86)\\NVDA\\louis\\tables\\braille-patterns.cti'], inbuf b'E\x00\x00\x00x\x00\x00\x00p\x00\x00\x00l\x00\x00\x00o\x00\x00\x00r\x00\x00\x00a\x00\x00\x00t\x00\x00\x00e\x00\x00\x00u\x00\x00\x00r\x00\x00\x00 \x00\x00\x00d\x00\x00\x00e\x00\x00\x00 \x00\x00\x00f\x00\x00\x00i\x00\x00\x00c\x00\x00\x00h\x00\x00\x00i\x00\x00\x00e\x00\x00\x00r\x00\x00\x00s\x00\x00\x00 \x00\x00\x00b\x00\x00\x00t\x00\x00\x00n\x00\x00\x00 \x00\x00\x00E\x00\x00\x00x\x00\x00\x00p\x00\x00\x00l\x00\x00\x00o\x00\x00\x00r\x00\x00\x00a\x00\x00\x00t\x00\x00\x00e\x00\x00\x00u\x00\x00\x00r\x00\x00\x00 \x00\x00\x00d\x00\x00\x00e\x00\x00\x00 \x00\x00\x00f\x00\x00\x00i\x00\x00\x00c\x00\x00\x00h\x00\x00\x00i\x00\x00\x00e\x00\x00\x00r\x00\x00\x00s\x00\x00\x00 \x00\x00\x00\xe9\x00\x00\x00p\x00\x00\x00i\x00\x00\x00n\x00\x00\x00g\x00\x00\x00l\x00\x00\x00\xe9\x00\x00\x00 \x00\x00\x002\x00\x00\x00/\x00\x00\x003\x00\x00\x00', typeform None, cursorPos c_long(0), mode 4
ERROR - eventHandler.executeEvent (14:49:54.829) - MainThread (17604):
